<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>가입 환영</title>
</head>
<body style="margin:0;">
<table width="600" border="0" cellpadding="0" cellspacing="0">
  <tbody>
  <tr>
    <td style="padding: 0 20px;">
      <table border="0" width="560" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
          <td></td>
        </tr>
        <tr>
          <td>
            <p>${siteName!} 홈페이지의 회원가입이 완료되었습니다.<br/>
              보다 쉽고 편하게 서비스를 이용하실 수 있습니다.<br/>
              감사합니다.
            </p>
          </td>
        </tr>
        <tr>
          <td>
            <a href="${link!}">홈페이지 바로가기</a>
          </td>
        </tr>
        </tbody>
      </table>
    </td>
  </tr>
  </tbody>
</table>
</body>
</html>